// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsrvtw4NzCQgb4lBDGepO_LANweWgxlXc',
    appId: '1:712575432967:web:8f3c02c01466964a9aeda2',
    messagingSenderId: '712575432967',
    projectId: 'vincentiusfernando-69ba2',
    authDomain: 'vincentiusfernando-69ba2.firebaseapp.com',
    databaseURL: 'https://vincentiusfernando-69ba2-default-rtdb.firebaseio.com',
    storageBucket: 'vincentiusfernando-69ba2.firebasestorage.app',
    measurementId: 'G-N5V5ZVLPCB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeNKQFje6VDWmLC2uz7qRmOnmerdap0Go',
    appId: '1:712575432967:android:c4bde8fc051fe0e39aeda2',
    messagingSenderId: '712575432967',
    projectId: 'vincentiusfernando-69ba2',
    databaseURL: 'https://vincentiusfernando-69ba2-default-rtdb.firebaseio.com',
    storageBucket: 'vincentiusfernando-69ba2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuCkdB-bluoJkAAzHQEMKu-CTETdUJW4A',
    appId: '1:712575432967:ios:ae1efb3bbd71f1bf9aeda2',
    messagingSenderId: '712575432967',
    projectId: 'vincentiusfernando-69ba2',
    databaseURL: 'https://vincentiusfernando-69ba2-default-rtdb.firebaseio.com',
    storageBucket: 'vincentiusfernando-69ba2.firebasestorage.app',
    iosBundleId: 'com.example.tugasPab2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuCkdB-bluoJkAAzHQEMKu-CTETdUJW4A',
    appId: '1:712575432967:ios:ae1efb3bbd71f1bf9aeda2',
    messagingSenderId: '712575432967',
    projectId: 'vincentiusfernando-69ba2',
    databaseURL: 'https://vincentiusfernando-69ba2-default-rtdb.firebaseio.com',
    storageBucket: 'vincentiusfernando-69ba2.firebasestorage.app',
    iosBundleId: 'com.example.tugasPab2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsrvtw4NzCQgb4lBDGepO_LANweWgxlXc',
    appId: '1:712575432967:web:1b03ae0acbc640d49aeda2',
    messagingSenderId: '712575432967',
    projectId: 'vincentiusfernando-69ba2',
    authDomain: 'vincentiusfernando-69ba2.firebaseapp.com',
    databaseURL: 'https://vincentiusfernando-69ba2-default-rtdb.firebaseio.com',
    storageBucket: 'vincentiusfernando-69ba2.firebasestorage.app',
    measurementId: 'G-KZT75G7HBM',
  );

}