// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDP_xbI_rabwE2d8TlZc8N4YMsKuCt7NQ',
    appId: '1:1059466709411:web:3ef78351b4b5ad3632b216',
    messagingSenderId: '1059466709411',
    projectId: 'vincentiusfernando-8afbc',
    authDomain: 'vincentiusfernando-8afbc.firebaseapp.com',
    databaseURL: 'https://vincentiusfernando-8afbc-default-rtdb.firebaseio.com',
    storageBucket: 'vincentiusfernando-8afbc.firebasestorage.app',
    measurementId: 'G-BXF8P886V0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJIk2kmWsUvzSk-HMlZDdODyIPaWwo3NQ',
    appId: '1:1059466709411:android:d57fcb5eca924b6532b216',
    messagingSenderId: '1059466709411',
    projectId: 'vincentiusfernando-8afbc',
    databaseURL: 'https://vincentiusfernando-8afbc-default-rtdb.firebaseio.com',
    storageBucket: 'vincentiusfernando-8afbc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCzfJfrqvE9NvlpCsuBGyy4MzXnVVJaLQ',
    appId: '1:1059466709411:ios:cb59cbbd7f97c12032b216',
    messagingSenderId: '1059466709411',
    projectId: 'vincentiusfernando-8afbc',
    databaseURL: 'https://vincentiusfernando-8afbc-default-rtdb.firebaseio.com',
    storageBucket: 'vincentiusfernando-8afbc.firebasestorage.app',
    iosBundleId: 'com.example.tugasPab2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCzfJfrqvE9NvlpCsuBGyy4MzXnVVJaLQ',
    appId: '1:1059466709411:ios:cb59cbbd7f97c12032b216',
    messagingSenderId: '1059466709411',
    projectId: 'vincentiusfernando-8afbc',
    databaseURL: 'https://vincentiusfernando-8afbc-default-rtdb.firebaseio.com',
    storageBucket: 'vincentiusfernando-8afbc.firebasestorage.app',
    iosBundleId: 'com.example.tugasPab2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDP_xbI_rabwE2d8TlZc8N4YMsKuCt7NQ',
    appId: '1:1059466709411:web:bc85dfe23ca4c82932b216',
    messagingSenderId: '1059466709411',
    projectId: 'vincentiusfernando-8afbc',
    authDomain: 'vincentiusfernando-8afbc.firebaseapp.com',
    databaseURL: 'https://vincentiusfernando-8afbc-default-rtdb.firebaseio.com',
    storageBucket: 'vincentiusfernando-8afbc.firebasestorage.app',
    measurementId: 'G-W7WCPD43HD',
  );
}
